permalink: /:year:month:day/:title
url: https://codigo8a.github.io/raiz.github.io
baseurl: /raiz.github.io

# variables
name: juandavid.site
description: Full Stack Developer experto en Sistematización de Procesos en la Nube, Jugador de PaintBall, Softcombat, Gomoso de la Robótica, Electrónica y La Tecnología.
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    coderay_line_numbers: false
    block:
      line_numbers: false
